export * from "./Answers/Answers"
export * from "./Loading/Loading"
export * from "./Questions/Questions"
export * from "./StartTrivia/StartTrivia"
export * from "./Score/Score"
export * from "./Question/Question"
export * from "./BtnNext/BtnNext"
export * from "./BtnFinish/BtnFinish"